affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
device: cuda
grid: 5
grid_eps: 0.02
grid_range:
- -1
- 1
k: 4
mult_arity: 2
round: 0
sb_trainable: true
sp_trainable: true
state_id: 2
symbolic.funs_name.0:
- - '0'
  - cos
  - 1/x
  - x^2
  - log
  - exp
  - exp
  - '0'
  - cos
  - exp
  - x^4
  - exp
  - tan
  - x
  - 1/x^3
  - 1/x^2
  - '0'
  - '0'
- - '0'
  - x
  - 1/x^2
  - x^2
  - x^2
  - exp
  - 1/x^2
  - 1/x^2
  - cos
  - exp
  - x^2
  - 1/x
  - tan
  - x
  - 1/x^3
  - '0'
  - '0'
  - 1/x^3
symbolic.funs_name.1:
- - cos
  - x
symbolic_enabled: true
width:
- - 18
  - 0
- - 2
  - 0
- - 1
  - 0
